# permissions for end users to edit vulnerabilityreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vulnerabilityreport-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: zora
    app.kubernetes.io/part-of: zora
    app.kubernetes.io/managed-by: kustomize
  name: vulnerabilityreport-editor-role
rules:
- apiGroups:
  - zora.undistro.io
  resources:
  - vulnerabilityreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zora.undistro.io
  resources:
  - vulnerabilityreports/status
  verbs:
  - get
