# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/zora.undistro.io_clusters.yaml
- bases/zora.undistro.io_plugins.yaml
- bases/zora.undistro.io_clusterissues.yaml
- bases/zora.undistro.io_clusterscans.yaml
- bases/zora.undistro.io_customchecks.yaml
- bases/zora.undistro.io_vulnerabilityreports.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_clusters.yaml
#- path: patches/webhook_in_plugins.yaml
#- path: patches/webhook_in_clusterissues.yaml
#- path: patches/webhook_in_clusterscans.yaml
#- path: patches/webhook_in_customchecks.yaml
#- path: patches/webhook_in_vulnerabilityreports.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_clusters.yaml
#- path: patches/cainjection_in_plugins.yaml
#- path: patches/cainjection_in_clusterissues.yaml
#- path: patches/cainjection_in_clusterscans.yaml
#- path: patches/cainjection_in_customchecks.yaml
#- path: patches/cainjection_in_vulnerabilityreports.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
