name: Kuttl Test

on:
  push:
    branches:
      - test-install

jobs:
  kuttl-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kind
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

      - name: Install Kubectl
      - uses: marcofranssen/setup-kubectl@v0.3.0
        id: kubectl
        with:
          kubectl-version: latest
      - run: echo ${{ steps.kubectl.output.kubectl-version }}

      - name: Set up Krew
      - uses: marcofranssen/setup-kubectl@v0.3.0
        with:
          enable-plugins: true
      - run: echo ${{ steps.kubectl.output.krew-version }}
      - run: kubectl krew install aws-auth

      - name: Run Kuttl tests
        run: |
          # Replace with your test command
          cd zora/tests && kubectl kuttl test
