name: Kuttl Test

on:
  push:
    branches:
      - test-install

jobs:
  kuttl-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kind
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

      - name: Install Kubectl
        uses: marcofranssen/setup-kubectl@v0.3.0
        with:
          kubectl-version: latest
        id: kubectl
      - run: echo ${{ steps.kubectl.outputs.kubectl-version }} # Fixed reference to outputs

      - name: Set up Krew
        uses: marcofranssen/setup-kubectl@v0.3.0 # Changed to setup-krew
        with:
          krew-version: latest
          update: true # Added to update Krew
      - run: |
          echo ${{ steps.krew.outputs.krew-version }} # Fixed reference to outputs
          kubectl krew install kuttl

      - name: Run Kuttl tests
        run: make test-installing